language: node_js
node_js: "lts/*"
before_script: npm install -g gatsby-cli
install: npm ci
script: npm run build
deploy:
  provider: pages
  token: $GITHUB_TOKEN
  skip_cleanup: true
  local_dir: public
  on:
    branch: master
